# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'paint.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./img/web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)

        #메뉴
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        
        #측면 툴바
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)

        #상단 툴바
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)

        #Save 버튼
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionSave.setShortcut('ctrl+S')
        
        #Load 버튼
        self.actionLoad = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./img/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon2)
        self.actionLoad.setObjectName("actionLoad")
        self.actionLoad.setShortcut('ctrl+L')

        #Exit 버튼
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon3)
        self.actionExit.setObjectName("actionExit")
        self.actionExit.setShortcut('ctrl+Q')
        self.actionExit.triggered.connect(quit)

        #Clear 버튼
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./img/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon4)
        self.actionClear.setObjectName("actionClear")
        self.actionClear.setShortcut('ctrl+C')

        #Line 버튼
        self.actionLine = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./img/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLine.setIcon(icon5)
        self.actionLine.setObjectName("actionLine")
        self.actionLine.setShortcut('alt+L')

        #Circle 버튼
        self.actionCircle = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./img/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCircle.setIcon(icon6)
        self.actionCircle.setObjectName("actionCircle")
        self.actionCircle.setShortcut('alt+C')

        #Rectangle 버튼
        self.actionrectangle = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./img/Rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionrectangle.setIcon(icon7)
        self.actionrectangle.setObjectName("actionrectangle")
        self.actionrectangle.setShortcut('alt+R')

        #Eraser 버튼
        self.actionEraser = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./img/Eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEraser.setIcon(icon8)
        self.actionEraser.setObjectName("actionEraser")
        self.actionEraser.setShortcut('alt+E')

        #Color 버튼
        self.actionColor = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./img/Color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionColor.setIcon(icon9)
        self.actionColor.setObjectName("actionColor")

        #File 버튼 자식
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        #Edit 버튼 자식
        self.menuEdit.addAction(self.actionLine)
        self.menuEdit.addAction(self.actionCircle)
        self.menuEdit.addAction(self.actionrectangle)
        self.menuEdit.addAction(self.actionEraser)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionColor)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        #측면 툴바
        self.toolBar.addAction(self.actionColor)
        self.toolBar.addAction(self.actionEraser)
        self.toolBar.addAction(self.actionLine)
        self.toolBar.addAction(self.actionCircle)
        self.toolBar.addAction(self.actionrectangle)
        #상단 툴바
        self.toolBar_2.addAction(self.actionSave)
        self.toolBar_2.addAction(self.actionLoad)
        self.toolBar_2.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Paint"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionCircle.setText(_translate("MainWindow", "Circle"))
        self.actionrectangle.setText(_translate("MainWindow", "Rectangle"))
        self.actionEraser.setText(_translate("MainWindow", "Eraser"))
        self.actionColor.setText(_translate("MainWindow", "Color"))



if __name__=="__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    sys.exit(app.exec_())
    